<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\HelloHandler::class => App\Handler\HelloHandlerFactory::class,
            App\Handler\LoginPageHandler::class => App\Handler\LoginPageHandlerFactory::class,
            App\Handler\RedirectHandler::class => App\Handler\RedirectHandlerFactory::class,
            App\LoginMiddleware::class => App\LoginMiddlewareFactory::class,
            App\OAuthAuthorizationMiddleware::class => App\OAuthAuthorizationMiddlewareFactory::class,
            App\XClacksOverheadMiddleware::class => App\XClacksOverheadMiddlewareFactory::class,
        ],
    ],
];
